/*
* Generated using  CanPacker version V0.01.
* Description file used is ./description.csv, edit the description, the regenerate the source code, do not edit this file manualy.
*/
#ifdef __cplusplus 
extern "C" 
{ 
#endif		/* __cplusplus */ 


#include "CAN_DEVICE.h"
#include <stdbool.h>






/* packing "	send device health data to others		"*/
bool HEALTH_pack(
    const uint32_t ID, 
    uint8_t * pU8Data
    /*uint32_t HEALTH_MULTIPLEXOR */ /*key */ /*is a constant no argument is used*/
    /*uint16_t  VOLTAGe_HEALTH */  /*value gotton from get_voltageUpdate()*/ ,
    const uint16_t  CURRENTHEALTH ,
    const ON_OFF_t  IO )
{
    uint64_t * pU64Data = (uint64_t *)(pU8Data);


    /*packing HEALTH_MULTIPLEXOR*/
    *pU64Data = (*pU64Data ) | (uint64_t)(((0x12&0xff))<<4);

    /*packing VOLTAGe_HEALTH*/
    *pU64Data = (*pU64Data ) | (uint64_t)(((get_voltageUpdate())& 0x3f)<<20);

    /*packing CURRENTHEALTH*/
        *pU64Data = (*pU64Data ) | (uint64_t)(((CURRENTHEALTH)& 0xff)<<32);

    /*packing IO*/
        *pU64Data = (*pU64Data ) | (uint64_t)(((IO)& 0x7)<<40);
    return true;
}

/* packing "	resets device		"*/
bool RESET_pack(
    const uint32_t ID, 
    uint8_t * pU8Data
    /*uint32_t RESET_CONSTANT */  /*is a constant no argument is used*/)
{
    uint64_t * pU64Data = (uint64_t *)(pU8Data);


    /*packing RESET_CONSTANT*/
    *pU64Data = (*pU64Data ) | (uint64_t)(((0x01020304&0xffffffff))<<7);
    return true;
}


/* unpacking "	send device health data to others		"*/
bool HEALTH_unpack(
    const uint32_t ID, 
    const uint8_t * pU8Data
    /*uint32_t HEALTH_MULTIPLEXOR*/ /*key */ /*is a constant no argument is used*/
    /*uint16_t * VOLTAGe_HEALTH*/  /*value set to set_voltageUpdate()*/ ,
    uint16_t * CURRENTHEALTH 
    /*ON_OFF_t * IO*/  /*value set to set_IO_ON_OFF()*/ )
{
    uint64_t * pU64Data = (uint64_t *)(pU8Data);

    /*check ID match*/ 
    if (10 != ID){return false;} 

    /*unpacking HEALTH_MULTIPLEXOR*/
    uint32_t HEALTH_MULTIPLEXOR_ = (uint32_t)(((* pU64Data)>>4)&0xff); 
    if(HEALTH_MULTIPLEXOR_!=0x12){return false;}

    /*unpacking VOLTAGe_HEALTH*/
    uint16_t VOLTAGe_HEALTH_ = (uint16_t)(((* pU64Data)>>20)&0x3f); 
    set_voltageUpdate(VOLTAGe_HEALTH_);

    /*unpacking CURRENTHEALTH*/
    uint16_t CURRENTHEALTH_ = (uint16_t)(((* pU64Data)>>32)&0xff); 
    if (CURRENTHEALTH !=0){* CURRENTHEALTH = CURRENTHEALTH_;} 

    /*unpacking IO*/
    ON_OFF_t IO_ = (ON_OFF_t)(((* pU64Data)>>40)&0x7); 
    set_IO_ON_OFF(IO_);
    return true;
}

/* unpacking "	resets device		"*/
bool RESET_unpack(
    const uint32_t ID, 
    const uint8_t * pU8Data
    /*uint32_t RESET_CONSTANT*/  /*is a constant no argument is used*/)
{
    uint64_t * pU64Data = (uint64_t *)(pU8Data);

    /*check ID match*/ 
    if ("	0x1233" != ID){return false;} 

    /*unpacking RESET_CONSTANT*/
    uint32_t RESET_CONSTANT_ = (uint32_t)(((* pU64Data)>>7)&0xffffffff); 
    if(RESET_CONSTANT_!=0x01020304){return false;}
    set_resetDeviceNow(RESET_CONSTANT_);
    return true;
}



#ifdef __cplusplus
}
#endif		/* __cplusplus */
